area:
  radius: 7000
  lat: 48.513969429467124
  lon: 15.628936886787415
keys:
  amenity:
    post_office:
      category: Postamt
      icon: postal
    post_box:
      category: Briefkasten
      icon: postal
    fuel:
      category: Tankstelle
      icon: fillingstation
    atm:
      category: Geldautomat
      icon: atm-2
    doctors:
      category: Arzt
      icon: medicine
    pharmacy:
      category: Apotheke
      icon: firstaid
#    restaurant:
#      category: Restaurant
#      icon: restaurant
    taxi:
      category: Taxi-Stand
      icon: taxi
  cuisine:
    heuriger:
      category: Heuriger
      icon: winetasting
  information:
    office:
      category: Touristeninformation
      icon: information
  leisure:
    playground:
      category: Spielplatz
      icon: playground
    sea_bath:
      category: Badeteich
      icon: water
  shop:
    bakery:
      category: Bäckerei
      icon: bread
    supermarket:
      category: Supermarkt
      icon: supermarket
  tourism:
    attraction:
      category: Sehenswürdigkeit
      icon: sight-2
    museum:
      category: Museum
      icon: arch
  craft:
    brewery:
      category: Brauerei
      icon: brewery1