area:
  radius: 7000
  lat: 48.513969429467124
  lon: 15.628936886787415
keys:
  amenity:
    - cafe
    - post_office
    - post_box
    - fuel
    - atm
    - doctors
    - pharmacy
    - taxi
  cuisine:
    - heuriger
    - regional
  information:
    - office
  leisure:
    - playground
    - sea_bath
  shop:
    - bakery
    - supermarket
  tourism:
    - attraction
    - museum
  craft:
    - brewery
  historic:
    - castle
